print('Sounds good! Let\'s gooo!')

adj1 = input('an adjective:').strip()
adj2 = input('an adjective:').strip()
noun1 = input('a noun:').strip()
noun2 = input('a noun:').strip()
noun3 = input('a noun:').strip()
verb = input('a verb:').strip()
noun4 = input('a noun:').strip()

print(f'{adj1}, {adj1}, {adj2} {noun1},')
print(f'How I wonder what you are.')
print(f'Up above the {noun2} you {verb},')
print(f'Like a {noun3} in the {noun4}.')
print(f'{adj1}, {adj1}, {adj2} {noun1},')
print(f'How I wonder what you are.')