print("Right-O! Let's begin!")

obligation = input('an obligation:').strip()
adj1 = input('an adjective:').strip()
relation = input('an interpersonal relation:').strip()
animal = input('an animal:').strip()
noun1 = input('a noun:').strip()
adj2 = input('an adjective:').strip()
noun2 = input('a noun:').strip()
noun3 = input('a noun:').strip()
verb1 = input('a verb:').strip()
clothing = input('an article of clothing:').strip()
sickness = input('an illness:').strip()
adj3 = input('an adjective:').strip()
verb2 = input('a verb:').strip()

print(f'If you are ever late for {obligation}, here is some {adj1} advice for you. Tell your {relation} that your {animal} ate your {noun1}. They will surely be {adj2} and let you off the {noun2}.')
print(f'On the off-{noun3} they don\'t believe you, you can always {verb1} yourself in a {clothing} and say you have {sickness}. That might be a bit {adj3}, though.')
print(f'Worst-case, you can always just {verb2} away.')